netlify_webhooks.default_form:
  path: '/admin/config/services/netlify-webhooks'
  defaults:
    _form: '\Drupal\netlify_webhooks\Form\DefaultForm'
    _title: 'Netlify Webhooks'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

