netlify_webhooks.default_form:
  title: 'Netlify Webhooks'
  route_name: netlify_webhooks.default_form
  description: 'Configure Netlify Webhooks'
  parent: system.admin_config_services



# Netlify build hook menu items definition
entity.netlify_build_hook.collection:
  title: 'Netlify build hook'
  route_name: entity.netlify_build_hook.collection
  description: 'List Netlify build hook (bundles)'
  parent: system.admin_structure
  weight: 99

